# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for .NET (NuGet)
  - package-ecosystem: "nuget"
    directory: "/CyberRadio.Code"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  
  # Enable security updates for .NET (NuGet)
  - package-ecosystem: "nuget"
    directory: "/CyberRadio.Code"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "security"
    open-pull-requests-limit: 10
