//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioExt_Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioExt_Helper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Song(s).
        /// </summary>
        internal static string AddSongsToolStrip {
            get {
                return ResourceManager.GetString("AddSongsToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Up Path.
        /// </summary>
        internal static string BackUpPath {
            get {
                return ResourceManager.GetString("BackUpPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the path to backup custom radio stations to..
        /// </summary>
        internal static string BackupPathHelp {
            get {
                return ResourceManager.GetString("BackupPathHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path set; radio stations will NOT be backed up&gt;.
        /// </summary>
        internal static string BackupPathPlaceholder {
            get {
                return ResourceManager.GetString("BackupPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Icon.
        /// </summary>
        internal static string CustomIcon {
            get {
                return ResourceManager.GetString("CustomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether or not you want to use a custom icon for the radio station..
        /// </summary>
        internal static string CustomIconHelp {
            get {
                return ResourceManager.GetString("CustomIconHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all songs?.
        /// </summary>
        internal static string DeleteAllSongsConfirm {
            get {
                return ResourceManager.GetString("DeleteAllSongsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Station.
        /// </summary>
        internal static string DeleteStation {
            get {
                return ResourceManager.GetString("DeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and Icon.
        /// </summary>
        internal static string DisplayAndIcon {
            get {
                return ResourceManager.GetString("DisplayAndIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DotDotDot {
            get {
                return ResourceManager.GetString("DotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Song Order.
        /// </summary>
        internal static string EditSongOrder {
            get {
                return ResourceManager.GetString("EditSongOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM:.
        /// </summary>
        internal static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to place the station at the right place in the stations list. If the station name has an FM number, it should be the same..
        /// </summary>
        internal static string FMHelp {
            get {
                return ResourceManager.GetString("FMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Base Path.
        /// </summary>
        internal static string GameBasePath {
            get {
                return ResourceManager.GetString("GameBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path set; game executable missing&gt;.
        /// </summary>
        internal static string GameBasePathPlaceholder {
            get {
                return ResourceManager.GetString("GameBasePathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Paths.
        /// </summary>
        internal static string GamePaths {
            get {
                return ResourceManager.GetString("GamePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get URL from Radio Garden.
        /// </summary>
        internal static string GetURLFromRadioGarden {
            get {
                return ResourceManager.GetString("GetURLFromRadioGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Use.
        /// </summary>
        internal static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon for the station, if you don&apos;t use a custom one. It can be any UIIcon record..
        /// </summary>
        internal static string IconHelp {
            get {
                return ResourceManager.GetString("IconHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink Atlas Part:.
        /// </summary>
        internal static string InkAtlasPart {
            get {
                return ResourceManager.GetString("InkAtlasPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink Atlas Path:.
        /// </summary>
        internal static string InkAtlasPath {
            get {
                return ResourceManager.GetString("InkAtlasPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which part of the .inkatlas should be used for the icon, e.g., gryphon_5.
        /// </summary>
        internal static string InkPartHelp {
            get {
                return ResourceManager.GetString("InkPartHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points to the .inkatlas that holds the icon texture..
        /// </summary>
        internal static string InkPathHelp {
            get {
                return ResourceManager.GetString("InkPathHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber Radio Assistant.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Station.
        /// </summary>
        internal static string NewStation {
            get {
                return ResourceManager.GetString("NewStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [New Station].
        /// </summary>
        internal static string NewStationListBoxEntry {
            get {
                return ResourceManager.GetString("NewStationListBoxEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Cyberpunk 2077 executable has not been set.\nPlease set it now..
        /// </summary>
        internal static string NoExeFound {
            get {
                return ResourceManager.GetString("NoExeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Game Path.
        /// </summary>
        internal static string NoGamePath {
            get {
                return ResourceManager.GetString("NoGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file did not look like Cyberpunk 2077. Please try again..
        /// </summary>
        internal static string NonCyberpunkExe {
            get {
                return ResourceManager.GetString("NonCyberpunkExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stations Yet!.
        /// </summary>
        internal static string NoStationsYet {
            get {
                return ResourceManager.GetString("NoStationsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to open the URL: .
        /// </summary>
        internal static string OpenURLErrorOccured {
            get {
                return ResourceManager.GetString("OpenURLErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radioExt GitHub.
        /// </summary>
        internal static string RadioExtGithub {
            get {
                return ResourceManager.GetString("RadioExtGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radioExt on NexusMods.
        /// </summary>
        internal static string RadioExtNexusMods {
            get {
                return ResourceManager.GetString("RadioExtNexusMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path set; radioExt is not installed&gt;.
        /// </summary>
        internal static string RadioExtPathPlaceholder {
            get {
                return ResourceManager.GetString("RadioExtPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to get a box where you can paste a URL from radio.garden and parse the final web stream..
        /// </summary>
        internal static string RadioGardenBtnHelp {
            get {
                return ResourceManager.GetString("RadioGardenBtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Stations Path.
        /// </summary>
        internal static string RadioStationPath {
            get {
                return ResourceManager.GetString("RadioStationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Stations.
        /// </summary>
        internal static string RefreshStations {
            get {
                return ResourceManager.GetString("RefreshStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Song(s).
        /// </summary>
        internal static string RemoveSongsToolStrip {
            get {
                return ResourceManager.GetString("RemoveSongsToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string SongArtistHeader {
            get {
                return ResourceManager.GetString("SongArtistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        internal static string SongFileSizeHeader {
            get {
                return ResourceManager.GetString("SongFileSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string SongLengthHeader {
            get {
                return ResourceManager.GetString("SongLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SongNameHeader {
            get {
                return ResourceManager.GetString("SongNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the name of your station that will be displayed in the game. Special characters are escaped properly..
        /// </summary>
        internal static string StationNameHelp {
            get {
                return ResourceManager.GetString("StationNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Settings.
        /// </summary>
        internal static string StreamSettings {
            get {
                return ResourceManager.GetString("StreamSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream URL:.
        /// </summary>
        internal static string StreamURL {
            get {
                return ResourceManager.GetString("StreamURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the web stream to use..
        /// </summary>
        internal static string StreamURLHelp {
            get {
                return ResourceManager.GetString("StreamURLHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + V) - Paste Radio Garden URL here.
        /// </summary>
        internal static string URLHint {
            get {
                return ResourceManager.GetString("URLHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Stream?.
        /// </summary>
        internal static string UseStream {
            get {
                return ResourceManager.GetString("UseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this station should use a web stream for its audio source..
        /// </summary>
        internal static string UseStreamHelp {
            get {
                return ResourceManager.GetString("UseStreamHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using?.
        /// </summary>
        internal static string Using_ {
            get {
                return ResourceManager.GetString("Using?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall volume multiplier for the station. Make sure all songs have the same volume, then adjust the overall volume of the station with this value to match up with vanilla stations..
        /// </summary>
        internal static string VolumeHelp {
            get {
                return ResourceManager.GetString("VolumeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently selected volume. Use the slider or double click value to change..
        /// </summary>
        internal static string VolumeValHelp {
            get {
                return ResourceManager.GetString("VolumeValHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
