//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioExt_Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioExt_Helper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        internal static string AboutGithubRepo {
            get {
                return ResourceManager.GetString("AboutGithubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool to help create and manage custom radio stations in Cyberpunk 2077 when using the radioExt Mod..
        /// </summary>
        internal static string AboutInfo {
            get {
                return ResourceManager.GetString("AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to.
        /// </summary>
        internal static string AboutSpecialThanks1 {
            get {
                return ResourceManager.GetString("AboutSpecialThanks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the awesome radioExt mod!.
        /// </summary>
        internal static string AboutSpecialThanks2 {
            get {
                return ResourceManager.GetString("AboutSpecialThanks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected  .
        /// </summary>
        internal static string AddSelected {
            get {
                return ResourceManager.GetString("AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select song files to add.
        /// </summary>
        internal static string AddSongs {
            get {
                return ResourceManager.GetString("AddSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Song(s).
        /// </summary>
        internal static string AddSongsToolStrip {
            get {
                return ResourceManager.GetString("AddSongsToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Export to Game?.
        /// </summary>
        internal static string AutoExportOption {
            get {
                return ResourceManager.GetString("AutoExportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, your stations will immediately export to the game after successfully exporting to staging..
        /// </summary>
        internal static string AutoExportOptionHelp {
            get {
                return ResourceManager.GetString("AutoExportOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates at Startup?.
        /// </summary>
        internal static string CheckForUpdatesOption {
            get {
                return ResourceManager.GetString("CheckForUpdatesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, enables the application to check for updates immediately after started..
        /// </summary>
        internal static string CheckForUpdatesOptionHelp {
            get {
                return ResourceManager.GetString("CheckForUpdatesOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the configuration to default values?.
        /// </summary>
        internal static string ConfigResetConfirm {
            get {
                return ResourceManager.GetString("ConfigResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the configuration. Please make sure the config.yml file exists..
        /// </summary>
        internal static string ConfigSaveError {
            get {
                return ResourceManager.GetString("ConfigSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved!.
        /// </summary>
        internal static string ConfigSaveSuccess {
            get {
                return ResourceManager.GetString("ConfigSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to refresh your stations from disk? You will lose any pending changes..
        /// </summary>
        internal static string ConfirmRefreshStations {
            get {
                return ResourceManager.GetString("ConfirmRefreshStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Icon.
        /// </summary>
        internal static string CustomIcon {
            get {
                return ResourceManager.GetString("CustomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether or not you want to use a custom icon for the radio station..
        /// </summary>
        internal static string CustomIconHelp {
            get {
                return ResourceManager.GetString("CustomIconHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all songs?.
        /// </summary>
        internal static string DeleteAllSongsConfirm {
            get {
                return ResourceManager.GetString("DeleteAllSongsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Station.
        /// </summary>
        internal static string DeleteStation {
            get {
                return ResourceManager.GetString("DeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        internal static string DisableAllStations {
            get {
                return ResourceManager.GetString("DisableAllStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Station.
        /// </summary>
        internal static string DisabledStation {
            get {
                return ResourceManager.GetString("DisabledStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Selected.
        /// </summary>
        internal static string DisableSelectedStation {
            get {
                return ResourceManager.GetString("DisableSelectedStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and Icon.
        /// </summary>
        internal static string DisplayAndIcon {
            get {
                return ResourceManager.GetString("DisplayAndIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DotDotDot {
            get {
                return ResourceManager.GetString("DotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Logs Path....
        /// </summary>
        internal static string EditLogsPathOption {
            get {
                return ResourceManager.GetString("EditLogsPathOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a folder dialog where you can choose a new path to save log files..
        /// </summary>
        internal static string EditLogsPathOptionHelp {
            get {
                return ResourceManager.GetString("EditLogsPathOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Paths....
        /// </summary>
        internal static string EditPathsOption {
            get {
                return ResourceManager.GetString("EditPathsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the path&apos;s dialog to edit the staging and game base path..
        /// </summary>
        internal static string EditPathsOptionHelp {
            get {
                return ResourceManager.GetString("EditPathsOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Song Order.
        /// </summary>
        internal static string EditSongOrder {
            get {
                return ResourceManager.GetString("EditSongOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        internal static string EnableAllStations {
            get {
                return ResourceManager.GetString("EnableAllStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled Stations: {0} / {1}.
        /// </summary>
        internal static string EnabledStationsCount {
            get {
                return ResourceManager.GetString("EnabledStationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Selected.
        /// </summary>
        internal static string EnableSelectedStation {
            get {
                return ResourceManager.GetString("EnableSelectedStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error pausing stream: {0}.
        /// </summary>
        internal static string ErrorPausingStream {
            get {
                return ResourceManager.GetString("ErrorPausingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error streaming audio: {0}.
        /// </summary>
        internal static string ErrorStreamingAudio {
            get {
                return ResourceManager.GetString("ErrorStreamingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Canceled.
        /// </summary>
        internal static string ExportCanceled {
            get {
                return ResourceManager.GetString("ExportCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported to Staging!.
        /// </summary>
        internal static string ExportCompleteStatus {
            get {
                return ResourceManager.GetString("ExportCompleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Export to Staging&quot; to export the stations above to the staging folder first.
        ///You will be able to review the stations before copying to the game directory.
        ///
        ///If something doesn&apos;t look correct, exit out of this window and make changes in the main application..
        /// </summary>
        internal static string ExportHelp {
            get {
                return ResourceManager.GetString("ExportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting station: {0}.
        /// </summary>
        internal static string ExportingStationStatus {
            get {
                return ResourceManager.GetString("ExportingStationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Stations.
        /// </summary>
        internal static string ExportStations {
            get {
                return ResourceManager.GetString("ExportStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Game.
        /// </summary>
        internal static string ExportToGame {
            get {
                return ResourceManager.GetString("ExportToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported to Game!.
        /// </summary>
        internal static string ExportToGameComplete {
            get {
                return ResourceManager.GetString("ExportToGameComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Staging.
        /// </summary>
        internal static string ExportToStaging {
            get {
                return ResourceManager.GetString("ExportToStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Only Enabled stations are 
        ///exported to the game..
        /// </summary>
        internal static string ExportWindowTip {
            get {
                return ResourceManager.GetString("ExportWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM:.
        /// </summary>
        internal static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to place the station at the right place in the stations list. If the station name has an FM number, it should be the same..
        /// </summary>
        internal static string FMHelp {
            get {
                return ResourceManager.GetString("FMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Base Path.
        /// </summary>
        internal static string GameBasePath {
            get {
                return ResourceManager.GetString("GameBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path set; game executable missing&gt;.
        /// </summary>
        internal static string GameBasePathPlaceholder {
            get {
                return ResourceManager.GetString("GameBasePathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Paths.
        /// </summary>
        internal static string GamePaths {
            get {
                return ResourceManager.GetString("GamePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Use.
        /// </summary>
        internal static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon for the station, if you don&apos;t use a custom one. It can be any UIIcon record..
        /// </summary>
        internal static string IconHelp {
            get {
                return ResourceManager.GetString("IconHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink Atlas Part:.
        /// </summary>
        internal static string InkAtlasPart {
            get {
                return ResourceManager.GetString("InkAtlasPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink Atlas Path:.
        /// </summary>
        internal static string InkAtlasPath {
            get {
                return ResourceManager.GetString("InkAtlasPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which part of the .inkatlas should be used for the icon, e.g., gryphon_5.
        /// </summary>
        internal static string InkPartHelp {
            get {
                return ResourceManager.GetString("InkPartHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points to the .inkatlas that holds the icon texture..
        /// </summary>
        internal static string InkPathHelp {
            get {
                return ResourceManager.GetString("InkPathHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stream - Will not work in game.
        /// </summary>
        internal static string InvalidStream {
            get {
                return ResourceManager.GetString("InvalidStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Streaming.
        /// </summary>
        internal static string IsStream {
            get {
                return ResourceManager.GetString("IsStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Path:.
        /// </summary>
        internal static string LogPathLabel {
            get {
                return ResourceManager.GetString("LogPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string LogSettings {
            get {
                return ResourceManager.GetString("LogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string LVDisplayName {
            get {
                return ResourceManager.GetString("LVDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Path.
        /// </summary>
        internal static string LVProposedPath {
            get {
                return ResourceManager.GetString("LVProposedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Count.
        /// </summary>
        internal static string LVSongCount {
            get {
                return ResourceManager.GetString("LVSongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string LVStationIcon {
            get {
                return ResourceManager.GetString("LVStationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled?.
        /// </summary>
        internal static string LVStationStatus {
            get {
                return ResourceManager.GetString("LVStationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream URL.
        /// </summary>
        internal static string LVStreamURL {
            get {
                return ResourceManager.GetString("LVStreamURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber Radio Assistant.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Every Launch?.
        /// </summary>
        internal static string NewLogFileOption {
            get {
                return ResourceManager.GetString("NewLogFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, specifies that a new log file will be created on every run of the app..
        /// </summary>
        internal static string NewLogFileOptionHelp {
            get {
                return ResourceManager.GetString("NewLogFileOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Station.
        /// </summary>
        internal static string NewStation {
            get {
                return ResourceManager.GetString("NewStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [New Station].
        /// </summary>
        internal static string NewStationListBoxEntry {
            get {
                return ResourceManager.GetString("NewStationListBoxEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Cyberpunk 2077 executable has not been set.
        ///Please set it now..
        /// </summary>
        internal static string NoExeFound {
            get {
                return ResourceManager.GetString("NoExeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Game Path.
        /// </summary>
        internal static string NoGamePath {
            get {
                return ResourceManager.GetString("NoGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection.
        /// </summary>
        internal static string NoInternetCaption {
            get {
                return ResourceManager.GetString("NoInternetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check for updates. Please check your internet and try again..
        /// </summary>
        internal static string NoInternetMsg {
            get {
                return ResourceManager.GetString("NoInternetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path&gt;.
        /// </summary>
        internal static string NoLogPathSet {
            get {
                return ResourceManager.GetString("NoLogPathSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Mod Installed.
        /// </summary>
        internal static string NoModInstalled {
            get {
                return ResourceManager.GetString("NoModInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file did not look like Cyberpunk 2077. Please try again..
        /// </summary>
        internal static string NonCyberpunkExe {
            get {
                return ResourceManager.GetString("NonCyberpunkExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the radioExt mod installed.
        ///Can&apos;t export radio stations to game..
        /// </summary>
        internal static string NoRadioExtMsg {
            get {
                return ResourceManager.GetString("NoRadioExtMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Staging Path.
        /// </summary>
        internal static string NoStagingPath {
            get {
                return ResourceManager.GetString("NoStagingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staging folder for radio stations is not yet set.
        ///Please set it now..
        /// </summary>
        internal static string NoStagingPathFound {
            get {
                return ResourceManager.GetString("NoStagingPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stations Yet!.
        /// </summary>
        internal static string NoStationsYet {
            get {
                return ResourceManager.GetString("NoStationsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the latest version. No update available..
        /// </summary>
        internal static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Date.
        /// </summary>
        internal static string NoUpdateCaption {
            get {
                return ResourceManager.GetString("NoUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Game Executable.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Game Radios Folder.
        /// </summary>
        internal static string OpenGameFolder {
            get {
                return ResourceManager.GetString("OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        internal static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Staging Folder.
        /// </summary>
        internal static string OpenStagingFolder {
            get {
                return ResourceManager.GetString("OpenStagingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to open the URL: .
        /// </summary>
        internal static string OpenURLErrorOccured {
            get {
                return ResourceManager.GetString("OpenURLErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse from radio.garden.
        /// </summary>
        internal static string ParseFromRadioGarden {
            get {
                return ResourceManager.GetString("ParseFromRadioGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths....
        /// </summary>
        internal static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radioExt GitHub.
        /// </summary>
        internal static string RadioExtGithub {
            get {
                return ResourceManager.GetString("RadioExtGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radioExt on NexusMods.
        /// </summary>
        internal static string RadioExtNexusMods {
            get {
                return ResourceManager.GetString("RadioExtNexusMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path set; radioExt is not installed&gt;.
        /// </summary>
        internal static string RadioExtPathPlaceholder {
            get {
                return ResourceManager.GetString("RadioExtPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the radio.garden URL from the web: .
        /// </summary>
        internal static string RadioGardenInput {
            get {
                return ResourceManager.GetString("RadioGardenInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Garden URL.
        /// </summary>
        internal static string RadioGardenURLCaption {
            get {
                return ResourceManager.GetString("RadioGardenURLCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Stations Path.
        /// </summary>
        internal static string RadioStationPath {
            get {
                return ResourceManager.GetString("RadioStationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Stations.
        /// </summary>
        internal static string RefreshStations {
            get {
                return ResourceManager.GetString("RefreshStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Remove Selected.
        /// </summary>
        internal static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Song(s).
        /// </summary>
        internal static string RemoveSongsToolStrip {
            get {
                return ResourceManager.GetString("RemoveSongsToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        internal static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the location to store log files.
        /// </summary>
        internal static string SelectLogPathDesc {
            get {
                return ResourceManager.GetString("SelectLogPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string SongArtistHeader {
            get {
                return ResourceManager.GetString("SongArtistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        internal static string SongFileSizeHeader {
            get {
                return ResourceManager.GetString("SongFileSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string SongLengthHeader {
            get {
                return ResourceManager.GetString("SongLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Listing.
        /// </summary>
        internal static string SongListing {
            get {
                return ResourceManager.GetString("SongListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SongNameHeader {
            get {
                return ResourceManager.GetString("SongNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Order.
        /// </summary>
        internal static string SongOrder {
            get {
                return ResourceManager.GetString("SongOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging Path.
        /// </summary>
        internal static string StagingPath {
            get {
                return ResourceManager.GetString("StagingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the radio station staging path..
        /// </summary>
        internal static string StagingPathHelp {
            get {
                return ResourceManager.GetString("StagingPathHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no path set; radio stations need to be staged first&gt;.
        /// </summary>
        internal static string StagingPathPlaceholder {
            get {
                return ResourceManager.GetString("StagingPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the name of your station that will be displayed in the game. Special characters are escaped properly..
        /// </summary>
        internal static string StationNameHelp {
            get {
                return ResourceManager.GetString("StationNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Settings.
        /// </summary>
        internal static string StreamSettings {
            get {
                return ResourceManager.GetString("StreamSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream URL:.
        /// </summary>
        internal static string StreamURL {
            get {
                return ResourceManager.GetString("StreamURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid stream URL..
        /// </summary>
        internal static string StreamURLError {
            get {
                return ResourceManager.GetString("StreamURLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the web stream to use..
        /// </summary>
        internal static string StreamURLHelp {
            get {
                return ResourceManager.GetString("StreamURLHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update for CRA. Do you want to open the downloader now?.
        /// </summary>
        internal static string UpdateAvailableNotice {
            get {
                return ResourceManager.GetString("UpdateAvailableNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        internal static string UpdateChangelog {
            get {
                return ResourceManager.GetString("UpdateChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates: {0}.
        /// </summary>
        internal static string UpdateCheckError {
            get {
                return ResourceManager.GetString("UpdateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        internal static string UpdateCurrentVersion {
            get {
                return ResourceManager.GetString("UpdateCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string UpdateDownloadButton {
            get {
                return ResourceManager.GetString("UpdateDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed! Starting the update....
        /// </summary>
        internal static string UpdateDownloadComplete {
            get {
                return ResourceManager.GetString("UpdateDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error: {0}.
        /// </summary>
        internal static string UpdateDownloadError {
            get {
                return ResourceManager.GetString("UpdateDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0}%.
        /// </summary>
        internal static string UpdateDownloadPercent {
            get {
                return ResourceManager.GetString("UpdateDownloadPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete. The containing folder will now be opened and the application will be closed..
        /// </summary>
        internal static string UpdateFolderOpening {
            get {
                return ResourceManager.GetString("UpdateFolderOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Folder.
        /// </summary>
        internal static string UpdateFolderOpeningCaption {
            get {
                return ResourceManager.GetString("UpdateFolderOpeningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version:.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Stream?.
        /// </summary>
        internal static string UseStream {
            get {
                return ResourceManager.GetString("UseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this station should use a web stream for its audio source..
        /// </summary>
        internal static string UseStreamHelp {
            get {
                return ResourceManager.GetString("UseStreamHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using?.
        /// </summary>
        internal static string Using_ {
            get {
                return ResourceManager.GetString("Using?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Songs.
        /// </summary>
        internal static string UsingSongs {
            get {
                return ResourceManager.GetString("UsingSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall volume multiplier for the station. Make sure all songs have the same volume, then adjust the overall volume of the station with this value to match up with vanilla stations..
        /// </summary>
        internal static string VolumeHelp {
            get {
                return ResourceManager.GetString("VolumeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently selected volume. Use the slider or double click value to change..
        /// </summary>
        internal static string VolumeValHelp {
            get {
                return ResourceManager.GetString("VolumeValHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
