name: Feature Request
description: Suggest a new feature for CRA.
title: "[FEAT]: "
labels: ["enhancement"]
assignees:
  - ethan-hann
body:
  - type: markdown
    attributes:
      value: "So, you have an idea for a new feature?! I'd love to know what it is."
  - type: textarea
    id: related-problem
    attributes:
      label: Related to a Problem?
      description: Is your feature request related to a current problem? Please describe the problem if so.
      placeholder: "ex. I'm always frustrated when ..."
    validations:
      required: false
  - type: textarea
    id: solution-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of what you want to happen.
      placeholder: "ex. Clicking this button should open this window and allow for some input ..."
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: "Provide a clear and concise description of any alternative solutions or features you've considered."
      placeholder: "ex. Alternatively, we could do this ..."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
