name: Translation Request
description: Submit a translation for CRA.
title: "[TRANSLATION] - [Language]"
labels: ["translation"]
assignees:
  - ethan-hann
body:
  - type: markdown
    attributes:
      value: "**For translation instructions, please refer to the [Localization Guide](https://ethan-hann.github.io/CyberRadio-Assistant/docs/advanced-topics/localization.html).**"
  - type: input
    id: language_name
    attributes:
      label: Language for Translation
      description: "Specify the language you are providing translations for (e.g., Italian, German)."
      placeholder: "e.g., Italian"
    validations:
      required: true
  - type: input
    id: culture_tag
    attributes:
      label: Culture Tag (.NET)
      description: "Provide the appropriate culture tag for the language (e.g., it for Italian)."
      placeholder: "e.g., it-IT"
      value: ""
    validations:
      required: true
  - type: markdown
    attributes:
      value: "**Upload your `translations.xlsx` file** to this issue for review and verification."



