name: Update version.json on Release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update version.json
      run: |
        VERSION=${{ github.event.release.tag_name }}
        URL=${{ github.event.release.html_url }}
        
        # Update the version.json file
        echo "{\"version\": \"${VERSION}\", \"url\": \"${URL}\"}" > version.json

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add version.json
        git commit -m "Update version.json for release ${{ github.event.release.tag_name }}"
        git push
